
name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up database credentials
        run: |
          echo "${{ secrets.DB_CREDS }}" > db_creds.yaml
          echo "${{ secrets.TARGET_DB_CREDS }}" > target_db_creds.yaml

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test

      - name: Clean up credentials files
        run: |
          rm db_creds.yaml
          rm target_db_creds.yaml
